#!/bin/bash
#
echo -n "Sisesta reisijate arv: "
read reisijaid
echo -n "Sisesta bussikohtade arv: "
read bussikohad
t2is=`expr $reisijaid / $bussikohad`
maha=`expr $reisijaid % $bussikohad`
#
if [ $maha -gt 0 ]
then
busse=$(( t2is +1 ))
else
busse=$t2is
fi
echo -n "$busse bussi on vaja.
"
#
