#!/bin/bash
#

osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"

echo -n "Select your os choice [1 or 2]? "
read osch

if [ $osch -eq 1 ] ; then
echo "you pick up unix (Sun Os)"
else #### nested if i.e if within if ######
if [ $osch -eq 2 ] ; then
echo "you pick up linux (Red Hat)"
else
echo "What you don't like Unix/Linux OS."
fi
fi
#
